name: 'auto-tag'
description: 'Automatically tag a new version!'
inputs:
  branch:
    description: 'Branch Name'
    required: true
outputs:
  last-build-number:
    description: "Latest previous build number"
    value: ${{ steps.get-last-build-number.outputs.last-build-number }}
  new-build-number:
    description: "Next incremental build number"
    value: ${{ steps.get-build-number.outputs.build-number }}
runs:
  using: "composite"
  steps:
    - run: BRANCH=${{ inputs.branch }} ${{ github.action_path }}/autotag.sh
      shell: bash
    # The following 'txt' files are created in autotag.sh
    - id: get-build-number
      run: echo "::set-output name=build-number::$(cat new_build_number.txt)"
      shell: bash
    - id: get-last-build-number
      run: echo "::set-output name=last-build-number::$(cat last_build_number.txt)"
      shell: bash
