name: Release Build

on: 
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The official version string (number, alphanumeric, etc)'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags - useful for tagging.
          fetch-depth: '0'

      - name: Run Build
        run: |
            TAG=${{ github.event.inputs.releaseVersion }} make

      - name: Cleanup Tag on Cancelled Workflow
        if: ${{ cancelled() }}
        run: |
          git push --delete origin ${{ github.event.inputs.releaseVersion }}

      - name: Clean Workspace
        if: always()
        run: |
          make ci_clean || echo "Unable to run ci_clean, working folder likely missing"
          sudo rm -rf "$GITHUB_WORKSPACE"/*
          sudo rm -rf "$GITHUB_WORKSPACE/.git"
